@Library("dsd-jenkins-k8s") _

deployProject (
    serviceName: "sonar-scala-demo",
    projectType: "maven",
    buildCommand: "mvn clean package -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080 -DskipTests=true",
    testCommand: "mvn test scoverage:report scala:compile -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080",
	sonarCommand: "mvn sonar:sonar -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080 -Dsonar.login=1ad066960082a3247a8020dd24a19cc6cd8ebc14",
    sonarQubeName: "SonarQubeDemo",
    skipDockerBuild: "true",
	skipDockerPush: "true",
    skipDeployment: "true",
    ignoreGitHeadMove: "true",
    targetEnv: "stg"
    )